color0 #033a27
color1 #fd4663
color2 #4efec0
color3 #35dffd
color4 #357afd
color5 #80fed2
color6 #81ebfe
color7 #f2f3f2
color8 #698078
color9 #fd4663
color10 #4efec0
color11 #35dffd
color12 #357afd
color13 #80fed2
color14 #81ebfe
color15 #f2f3f2

cursor                #f2f3f2
cursor_text_color     #033a27
background            #033a27
foreground            #f2f3f2
selection_foreground  #afb6b4
selection_background  #084933
active_border_color   #4efec0
inactive_border_color #084933
url_color             #4efec0

active_tab_foreground   #182520
active_tab_background   #4efec0
inactive_tab_foreground #afb6b4
inactive_tab_background #084933
cursor_trail_color      #afb6b4
